defaults: &defaults
  email_from: "no-reply@example.gov"
  email_encryption_key: 'notasecret'
  sponsor_count_min: 5
  sponsor_count_max: 20
  sponsor_moderation_threshold: 5
  petition_duration: 6
  host_for_email: <%= ENV.fetch('EPETITIONS_HOST').inspect %>
  email_protocol: http

development:
  <<: *defaults

test:
  <<: *defaults
  email_protocol: https

production:
  <<: *defaults
  email_protocol: https
