defaults: &defaults
  email_from: "no-reply@example.gov"
  email_encryption_key: 'notasecret'
  sponsor_count_min: 5
  sponsor_count_max: 20
  sponsor_moderation_threshold: 5
  petition_duration: 6
  email_protocol: http

development:
  <<: *defaults
  host_for_email: "localhost:3000"

development_with_caching:
  <<: *defaults
  host_for_email: "localhost:3000"

test:
  <<: *defaults
  host_for_email: "www.example.com"
  sponsor_count_min: 5
  sponsor_count_max: 20
  sponsor_moderation_threshold: 5
  email_protocol: https
