development: &DEV
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test: &TEST
  solr:
    hostname: localhost
    port: 8987
    log_level: WARNING
    path: /solr/test

cucumber:
  <<: *TEST

production: &PROD
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
  auto_commit_after_request: false

staging:
  <<: *PROD
